import React from 'react';
import { Sparkles, Lightbulb, Target, Layers, Star, ListChecks } from 'lucide-react';

export interface RelevancyExplanationData {
  similarity_score?: number | null;
  why_relevant?: string | null;
  similar_projects_summary?: string | null;
  objectives_overlap?: string | null;
  problem_domains_overlap?: string | null;
  unique_aspects?: string | null;
  novelty_suggestions?: string[];
  ollama_model?: string | null;
  status?: string | null;
}

interface RelevancyExplanationPanelProps {
  explanation: RelevancyExplanationData | null | undefined;
  similarityScore?: number | null;
  className?: string;
}

export default function RelevancyExplanationPanel({
  explanation,
  similarityScore,
  className = '',
}: RelevancyExplanationPanelProps) {
  const score = explanation?.similarity_score ?? similarityScore;

  if (!explanation?.why_relevant) {
    return (
      <div
        className={`rounded-xl border border-gray-200 dark:border-gray-700 bg-gray-50 dark:bg-gray-900/50 p-6 ${className}`}
      >
        <div className="flex items-center gap-2 text-gray-600 dark:text-gray-400">
          <Sparkles className="w-5 h-5" />
          <p className="text-sm">AI explanation is not available for this project yet.</p>
        </div>
      </div>
    );
  }

  return (
    <div
      className={`rounded-xl border-2 border-purple-200 dark:border-purple-800 bg-gradient-to-br from-purple-50 to-pink-50 dark:from-purple-950/30 dark:to-pink-950/30 p-6 ${className}`}
    >
      <div className="flex items-center justify-between gap-4 mb-4">
        <div className="flex items-center gap-2">
          <Sparkles className="w-6 h-6 text-purple-600 dark:text-purple-400" />
          <h3 className="text-lg font-bold text-gray-900 dark:text-white">AI Relevancy Explanation</h3>
        </div>
        {score != null && (
          <div className="text-sm font-semibold text-purple-900 dark:text-purple-200">
            Similarity Score: {Math.round(score)}%
          </div>
        )}
      </div>

      <div className="space-y-4">
        <Section icon={Target} title="Why Similar / Relevant" text={explanation.why_relevant} />
        {explanation.similar_projects_summary && (
          <Section icon={Layers} title="AI Similarity Summary" text={explanation.similar_projects_summary} />
        )}
        {explanation.objectives_overlap && (
          <Section icon={ListChecks} title="Objectives Overlap" text={explanation.objectives_overlap} />
        )}
        {explanation.problem_domains_overlap && (
          <Section icon={Target} title="Problem Domains Overlap" text={explanation.problem_domains_overlap} />
        )}
        {explanation.unique_aspects && (
          <Section icon={Star} title="Unique Aspects" text={explanation.unique_aspects} />
        )}
        {explanation.novelty_suggestions && explanation.novelty_suggestions.length > 0 && (
          <div className="bg-white dark:bg-gray-800 rounded-lg p-4 border border-purple-200 dark:border-purple-800">
            <div className="flex items-center gap-2 mb-2">
              <Lightbulb className="w-4 h-4 text-amber-600 dark:text-amber-400" />
              <div className="text-sm font-semibold text-purple-900 dark:text-purple-300">Suggestions</div>
            </div>
            <ul className="list-disc list-inside space-y-1 text-sm text-gray-700 dark:text-gray-300">
              {explanation.novelty_suggestions.map((item, index) => (
                <li key={index}>{item}</li>
              ))}
            </ul>
          </div>
        )}
      </div>

      {explanation.ollama_model && (
        <p className="mt-4 text-xs text-gray-500 dark:text-gray-400">
          Generated by {explanation.ollama_model}
          {explanation.status === 'fallback' ? ' (fallback — Ollama unavailable)' : ''}
        </p>
      )}
    </div>
  );
}

function Section({
  icon: Icon,
  title,
  text,
}: {
  icon: React.ComponentType<{ className?: string }>;
  title: string;
  text: string;
}) {
  return (
    <div className="bg-white dark:bg-gray-800 rounded-lg p-4 border border-purple-200 dark:border-purple-800">
      <div className="flex items-center gap-2 mb-2">
        <Icon className="w-4 h-4 text-purple-600 dark:text-purple-400" />
        <div className="text-sm font-semibold text-purple-900 dark:text-purple-300">{title}</div>
      </div>
      <p className="text-sm text-gray-700 dark:text-gray-300">{text}</p>
    </div>
  );
}
